import React, { useState, useEffect } from 'react';
import { Layout } from '../components/Layout';
import { Card } from '../components/Card';
import { FileOutput, Download, Loader2, FileText } from 'lucide-react';
import toast from 'react-hot-toast';
import api from '../utils/api';

export const ExportFormats = () => {
  const [papers, setPapers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [exporting, setExporting] = useState(null);

  useEffect(() => { fetchPapers(); }, []);

  const fetchPapers = async () => {
    try {
      const res = await api.get('/api/papers/');
      const data = res.data;
      // Handle both paginated ({results: [...]}) and plain array responses
      setPapers(Array.isArray(data) ? data : (data.results || []));
    } catch { toast.error('Failed to load papers'); }
    finally { setLoading(false); }
  };

  const exportAsDocx = (paper) => {
    setExporting(paper.id + '_docx');
    const questions = paper.questions_detail || [];
    const lines = [
      'QUESTION PAPER', `Subject: ${paper.subject}`,
      `Date: ${new Date().toLocaleDateString()}`, `Total: ${questions.length} questions`,
      `Generated by ExamForge AI`, '', '='.repeat(60), '',
      ...questions.map((q, i) => `Q${i + 1}. ${typeof q === 'string' ? q : q.text || ''}\n`),
      '', '='.repeat(60), 'End of Paper'
    ].join('\n');
    const blob = new Blob([lines], { type: 'application/msword' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${paper.subject}_ExamForge.doc`; a.click();
    URL.revokeObjectURL(url);
    toast.success('Word document downloaded!');
    setExporting(null);
  };

  const exportAsLatex = (paper) => {
    setExporting(paper.id + '_latex');
    const questions = paper.questions_detail || [];
    const latex = `\\documentclass[12pt]{article}\n\\usepackage[margin=1in]{geometry}\n\\title{${paper.subject}}\n\\begin{document}\n\\maketitle\n\\begin{enumerate}\n${
      questions.map((q, i) => {
        const text = (typeof q === 'string' ? q : q.text || '').replace(/&/g, '\\&');
        const marks = typeof q === 'object' ? q.marks : '';
        return `  \\item ${text}${marks ? ` \\hfill [${marks} marks]` : ''}`;
      }).join('\n')
    }\n\\end{enumerate}\n\\end{document}`;
    const blob = new Blob([latex], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${paper.subject}_ExamForge.tex`; a.click();
    URL.revokeObjectURL(url);
    toast.success('LaTeX file downloaded!');
    setExporting(null);
  };

  const exportAsCSV = (paper) => {
    setExporting(paper.id + '_csv');
    const questions = paper.questions_detail || [];
    const rows = [
      ['#','Question','Marks','Difficulty','Subject'],
      ...questions.map((q, i) => [
        i + 1,
        `"${(typeof q === 'string' ? q : q.text || '').replace(/"/g, '""')}"`,
        typeof q === 'object' ? q.marks : '',
        typeof q === 'object' ? q.difficulty || '' : '',
        paper.subject
      ])
    ].map(r => r.join(',')).join('\n');
    const blob = new Blob([rows], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url; a.download = `${paper.subject}_ExamForge.csv`; a.click();
    URL.revokeObjectURL(url);
    toast.success('CSV exported!');
    setExporting(null);
  };

  return (
    <Layout>
      <div className="space-y-6">
        <div className="relative bg-gradient-to-r from-teal-600 via-emerald-600 to-green-600 rounded-2xl p-7 text-white shadow-xl overflow-hidden">
          <div className="absolute -top-16 -right-16 w-64 h-64 bg-white/10 rounded-full blur-3xl pointer-events-none" />
          <div className="relative z-10">
            <div className="flex items-center gap-2 mb-2">
              <FileOutput className="w-5 h-5 text-emerald-200" />
              <span className="text-emerald-200 text-sm font-medium uppercase tracking-wider">Module 12</span>
            </div>
            <h2 className="text-3xl font-extrabold tracking-tight">Advanced Export Formats</h2>
            <p className="text-emerald-100 mt-1 text-sm">Download papers as Word (.doc), LaTeX (.tex), or CSV</p>
          </div>
        </div>
        {loading ? (
          <div className="flex items-center justify-center h-64"><Loader2 className="w-8 h-8 animate-spin text-emerald-500" /></div>
        ) : papers.length === 0 ? (
          <Card className="p-12 text-center text-gray-400">No generated papers found.</Card>
        ) : (
          <div className="space-y-4">
            {papers.map(paper => (
              <Card key={paper.id} className="p-5">
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                  <div className="flex items-center gap-3">
                    <div className="p-3 bg-emerald-100 dark:bg-emerald-900/30 rounded-xl">
                      <FileText className="w-5 h-5 text-emerald-600" />
                    </div>
                    <div>
                      <p className="font-bold text-gray-900 dark:text-white">{paper.subject}</p>
                      <p className="text-xs text-gray-400">{(paper.questions || []).length} questions · {new Date(paper.created_at).toLocaleDateString()}</p>
                    </div>
                  </div>
                  <div className="flex flex-wrap gap-2">
                    {[
                      { label: 'Word (.doc)', fn: exportAsDocx, key: '_docx', color: 'bg-blue-600 hover:bg-blue-700' },
                      { label: 'LaTeX (.tex)', fn: exportAsLatex, key: '_latex', color: 'bg-orange-600 hover:bg-orange-700' },
                      { label: 'CSV', fn: exportAsCSV, key: '_csv', color: 'bg-emerald-600 hover:bg-emerald-700' },
                    ].map(btn => (
                      <button key={btn.key} onClick={() => btn.fn(paper)} disabled={!!exporting}
                        className={`flex items-center gap-1.5 px-4 py-2 ${btn.color} text-white text-xs font-bold rounded-xl transition-all disabled:opacity-50`}>
                        {exporting === paper.id + btn.key ? <Loader2 className="w-3.5 h-3.5 animate-spin" /> : <Download className="w-3.5 h-3.5" />}
                        {btn.label}
                      </button>
                    ))}
                  </div>
                </div>
              </Card>
            ))}
          </div>
        )}
      </div>
    </Layout>
  );
};

export default ExportFormats;
