import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { Layout } from '../components/Layout';
import { Card } from '../components/Card';
import { Button } from '../components/Button';
import { Download, ArrowLeft, Printer } from 'lucide-react';
import jsPDF from 'jspdf';
import toast from 'react-hot-toast';

export const QuestionPaper = () => {
  const navigate = useNavigate();
  const [paperData, setPaperData] = useState(null);

  useEffect(() => {
    const saved = sessionStorage.getItem('generated_paper');
    if (saved) {
      setPaperData(JSON.parse(saved));
    } else {
      navigate('/dashboard');
    }
  }, [navigate]);

  if (!paperData) {
    return null;
  }

  const totalMarks = paperData.questions.reduce((sum, q) => sum + q.marks, 0);

  // Group questions by marks for sectioning
  const questionsByMarks = paperData.questions.reduce((acc, question) => {
    if (!acc[question.marks]) {
      acc[question.marks] = [];
    }
    acc[question.marks].push(question);
    return acc;
  }, {});

  const sections = Object.entries(questionsByMarks)
    .sort(([a], [b]) => parseInt(a) - parseInt(b))
    .map(([marks, questions], index) => ({
      name: String.fromCharCode(65 + index), // A, B, C, etc.
      marks: parseInt(marks),
      questions,
    }));

  const handleDownloadPDF = () => {
    try {
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      let yPos = 20;

      // Header Box
      doc.setFillColor(59, 130, 246); // Blue-500
      doc.rect(0, 0, pageWidth, 40, 'F');
      
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(24);
      doc.setFont('helvetica', 'bold');
      doc.text('EXAM FORGE', pageWidth / 2, 20, { align: 'center' });
      
      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.text('Official Question Paper', pageWidth / 2, 30, { align: 'center' });

      yPos = 55;
      doc.setTextColor(0, 0, 0);
      
      // Subject and Marks
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(`Subject: ${paperData.subject}`, margin, yPos);
      doc.text(`Max Marks: ${totalMarks}`, pageWidth - margin, yPos, { align: 'right' });
      yPos += 15;

      // Instructions
      doc.setDrawColor(200, 200, 200);
      doc.line(margin, yPos, pageWidth - margin, yPos);
      yPos += 10;
      
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.text('General Instructions:', margin, yPos);
      yPos += 8;
      
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const instructions = [
        '1. All questions are compulsory.',
        '2. Figures to the right indicate full marks.',
        '3. Use of calculators is permitted unless specified otherwise.',
        '4. Write clearly and show all necessary steps.'
      ];
      
      instructions.forEach(inst => {
        doc.text(inst, margin + 5, yPos);
        yPos += 6;
      });
      yPos += 10;

      // Sections and Questions
      let questionNumber = 1;
      sections.forEach((section) => {
        if (yPos > 240) {
          doc.addPage();
          yPos = 20;
        }

        // Section Header
        doc.setFillColor(243, 244, 246);
        doc.rect(margin, yPos - 5, pageWidth - 2 * margin, 10, 'F');
        doc.setFontSize(12);
        doc.setFont('helvetica', 'bold');
        doc.text(
          `SECTION ${section.name} - Questions of ${section.marks} mark${section.marks > 1 ? 's' : ''} each`,
          margin + 5,
          yPos + 2
        );
        yPos += 15;

        // Questions
        doc.setFontSize(11);
        doc.setFont('helvetica', 'normal');

        section.questions.forEach((question) => {
          const questionText = `${questionNumber}. ${question.text}`;
          const lines = doc.splitTextToSize(questionText, pageWidth - 2 * margin - 15);
          
          if (yPos + (lines.length * 7) > 270) {
            doc.addPage();
            yPos = 25;
          }

          lines.forEach((line, index) => {
            doc.text(line, margin, yPos);
            if (index === 0) {
              doc.text(`[${question.marks}]`, pageWidth - margin, yPos, { align: 'right' });
            }
            yPos += 7;
          });

          yPos += 5; // Space between questions
          questionNumber++;
        });

        yPos += 10; // Space between sections
      });

      // Footer
      const date = new Date().toLocaleDateString();
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated by ExamForge on ${date} | Page ${doc.internal.getNumberOfPages()}`, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, {
        align: 'center',
      });

      doc.save(`${paperData.subject.replace(/\s+/g, '_')}_Paper.pdf`);
      toast.success('PDF downloaded successfully!');
    } catch (error) {
      console.error('PDF Generation Error:', error);
      toast.error('Failed to generate PDF.');
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <Layout>
      <div className="space-y-6">
        {/* Action Buttons Strip */}
        <div className="flex flex-wrap items-center justify-between gap-4 print:hidden bg-white dark:bg-slate-800 p-4 rounded-2xl border border-gray-100 dark:border-slate-700 shadow-sm">
          <div className="flex gap-3">
            <Button variant="secondary" onClick={() => navigate('/dashboard')} className="rounded-xl">
              <ArrowLeft className="w-4 h-4 mr-2" />
              Return
            </Button>
          </div>
          <div className="flex gap-3">
            <Button variant="primary" onClick={handleDownloadPDF} className="rounded-xl shadow-lg shadow-blue-500/20">
              <Download className="w-4 h-4 mr-2" />
              Download PDF
            </Button>
            <Button variant="outline" onClick={handlePrint} className="rounded-xl">
              <Printer className="w-4 h-4 mr-2" />
              Print
            </Button>
          </div>
        </div>

        {/* Question Paper Preview */}
        <div className="max-w-4xl mx-auto pb-20">
          <Card noPadding className="overflow-hidden border-none shadow-2xl print:shadow-none bg-white dark:bg-slate-900">
            {/* Official Paper Header */}
            <div className="bg-gradient-to-br from-gray-900 to-slate-800 dark:from-slate-800 dark:to-slate-950 p-10 text-center text-white relative">
              <div className="absolute top-0 left-0 w-full h-1 bg-blue-600" />
              <h1 className="text-4xl font-black tracking-tighter uppercase mb-2">Institutional Question Paper</h1>
              <div className="flex items-center justify-center space-x-4 text-blue-200 uppercase tracking-widest text-xs font-bold">
                <span>{paperData.subject}</span>
                <span className="w-1.5 h-1.5 bg-blue-500 rounded-full" />
                <span>Max Marks: {totalMarks}</span>
              </div>
            </div>

            <div className="p-8 md:p-12 space-y-10">
              {/* Instructions Box */}
              <div className="bg-slate-50 dark:bg-slate-800/50 p-6 rounded-2xl border border-slate-100 dark:border-slate-700/50">
                <h3 className="text-sm font-black text-slate-900 dark:text-white uppercase tracking-wider mb-3">General Instructions:</h3>
                <ul className="space-y-2">
                  {[
                    'All questions are compulsory and carry specified marks.',
                    'Read each question carefully before attempting.',
                    'Check your subject code and total marks before starting.',
                    'Electronic gadgets are strictly prohibited unless specified.'
                  ].map((inst, i) => (
                    <li key={i} className="flex items-start text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
                      <span className="font-bold mr-3 text-blue-600">{i + 1}.</span>
                      {inst}
                    </li>
                  ))}
                </ul>
              </div>

              {/* Sections Map */}
              {sections.map((section, sectionIndex) => (
                <div key={sectionIndex} className="space-y-6">
                  {/* Section Title Strip */}
                  <div className="flex items-center gap-4">
                    <div className="flex-shrink-0 bg-blue-600 text-white w-12 h-12 rounded-xl flex items-center justify-center text-xl font-black shadow-lg shadow-blue-500/20">
                      {section.name}
                    </div>
                    <div className="flex-1">
                      <h3 className="text-xl font-black text-slate-900 dark:text-white tracking-tight uppercase">
                        Section {section.name}
                      </h3>
                      <p className="text-xs font-bold text-slate-400 dark:text-slate-500 uppercase tracking-widest">
                        {section.questions.length} Questions • {section.marks} Marks Each
                      </p>
                    </div>
                    <div className="h-px bg-slate-100 dark:bg-slate-800 flex-1 hidden md:block" />
                  </div>

                  {/* Question Grid */}
                  <div className="space-y-4 pl-0 md:pl-4">
                    {section.questions.map((question, qIndex) => {
                      const questionNumber =
                        sections
                          .slice(0, sectionIndex)
                          .reduce((sum, s) => sum + s.questions.length, 0) +
                        qIndex +
                        1;

                      return (
                        <div
                          key={question.id}
                          className="group flex items-start space-x-5 p-5 rounded-2xl hover:bg-slate-50 dark:hover:bg-slate-800/40 transition-all border border-transparent hover:border-slate-100 dark:hover:border-slate-700/50"
                        >
                          <div className="flex-shrink-0 w-8 h-8 bg-slate-100 dark:bg-slate-800 rounded-lg flex items-center justify-center text-sm font-bold text-slate-500 group-hover:bg-blue-600 group-hover:text-white transition-colors">
                            {questionNumber}
                          </div>
                          <div className="flex-1">
                            <p className="text-slate-800 dark:text-slate-200 text-lg leading-relaxed font-medium">
                              {question.text}
                            </p>
                          </div>
                          <div className="flex-shrink-0 pt-1">
                            <span className="text-xs font-black text-blue-600 dark:text-blue-400 bg-blue-50 dark:bg-blue-900/30 px-3 py-1 rounded-full uppercase tracking-widest border border-blue-100 dark:border-blue-900/50">
                              {question.marks}M
                            </span>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              ))}

              {/* Official Footer */}
              <div className="pt-12 border-t-2 border-dashed border-slate-100 dark:border-slate-800 text-center">
                <p className="text-xs font-bold text-slate-400 uppercase tracking-[0.3em] mb-2">End of Question Paper</p>
                <div className="flex items-center justify-center space-x-2 text-[10px] text-slate-400">
                  <span>Generated by ExamForge AI Repository</span>
                  <span className="w-1 h-1 bg-slate-300 rounded-full" />
                  <span>{new Date().toLocaleDateString()}</span>
                </div>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </Layout>
  );

};
